#pragma once
#include <IMUData.hpp>
#include <BNO055SensorInterface.hpp>
#include <ISensor.hpp>
#include <Logger.hpp>
#include "nvs_flash.h"
#include "nvs.h"

/**
 * @brief BNO055 sensor class
 * 
 */
class BNO055Sensor : public ISensor
{
public:
    /** @brief Construct a new BNO055 sensor wrapper. */
    BNO055Sensor(I2CBus* bus, uint8_t address);

    /**
     * @brief Initialize the BNO055 device and prepare it for measurements.
     * @return true on success, false otherwise.
     */
    bool init() override;
    bool updateData() override;
    bool hardwareTest();

    /**
     * @brief Getter for the sensor data
     * 
    * @return the IMUData structure containing the latest readings 
     */
    IMUData getData();

    /**
     * @brief Check if the sensor is fully calibrated
     * @return true if all sensor components report a calibration status of 3
     */
    bool isFullyCalibrated();

    /** 
     * @brief Save the sensor calibration data to NVS.
     */
    bool saveCalibrationToNVS();
    
    /** 
     * @brief Load the sensor calibration data from NVS.
     */
    bool loadCalibrationFromNVS();

private:
    // Interface to the BNO055 sensor using low-level APIs
    BNO055SensorInterface _bno_interface;

    // Data generated by the sensor
    IMUData _data{"BNO055"};

    // Flag to track if calibration file was successfully loaded
    bool _calibration_restored = false;
};