#pragma once
#include <ISensor.hpp>
#include <LIS3DHTR.h>
#include <Wire.h>
#include <config.h>
#include <AccelerometerSensorData.hpp>

/**
 * @brief LIS3DHTR sensor class
 * 
 */
class LIS3DHTRSensor : public ISensor
{
public:
    LIS3DHTRSensor();
    bool init() override;
    bool updateData() override;

    /**
     * @brief Getter for the sensor data
     * 
     * @return a shared pointer to the AccelerometerData structure containing the latest readings
     */
    std::shared_ptr<AccelerometerSensorData> getData();

private:
    // Interface to the LIS3DHTR sensor using low-level APIs
    LIS3DHTR<TwoWire> _lis;

    // Data generated by the sensor
    std::shared_ptr<AccelerometerSensorData> _data;
};