#pragma once
#include <PressureSensorData.hpp>
#include <ISensor.hpp>
#include <Adafruit_MPRLS.h>

/**
 * @brief MPRLS sensor class
 * 
 */
class MPRLSSensor : public ISensor
{
public:
    MPRLSSensor();
    bool init() override;
    bool updateData() override;

    /**
     * @brief Getter for the sensor data
     * 
     * @return a shared pointer to the PressureSensorData structure containing the latest readings
     */
    std::shared_ptr<PressureSensorData> getData();

private:
    // Interface to the MPRLS sensor using Adafruit library
    Adafruit_MPRLS _mprls;

    // Data generated by the sensor
    std::shared_ptr<PressureSensorData> _data;
};
