#pragma once

#include <ISensor.hpp>
#include <Wire.h>
#include <SparkFun_u-blox_GNSS_Arduino_Library.h>
#include <config.h>
#include <GPSData.hpp>

/**
 * @brief GPS sensor class
 * 
 */
class GPS : public ISensor
{
public:
    GPS();
    bool init() override;
    bool updateData() override;

    /**
     * @brief Getter for the sensor data
     * 
     * @return a shared pointer to the GPSData structure containing the latest readings
     */
    std::shared_ptr<GPSData> getData();

private:
    // SparkFun u-blox GNSS library interface object
    SFE_UBLOX_GNSS _myGNSS;

    // Data generated by the sensor
    std::shared_ptr<GPSData> _data;
};