#include "board.h"
#include "sdkconfig.h"
#include "config.h"
#include "driver/gpio.h"
#include "esp_err.h"
#include "esp_event.h"
#include "SerialLogger.hpp"
#include "esp_netif.h"
#include "esp_partition.h"
#include "esp_wifi.h"
#include "nvs_flash.h"
#include <cstring>

static const char *TAG = "MannyBoard";

/**
 * @brief SoftAP values read from sdkconfig.
 */
struct MannyWifiApConfig {
    const char* ssid;
    const char* password;
    const char* ip;
    const char* netmask;
    uint8_t channel;
    uint8_t max_connections;
};

static_assert(sizeof(CONFIG_ROCKET_AP_SSID) > 1,
              "CONFIG_ROCKET_AP_SSID must not be empty");
static_assert(sizeof(CONFIG_ROCKET_AP_PASSWORD) == 1 ||
              sizeof(CONFIG_ROCKET_AP_PASSWORD) >= 9,
              "CONFIG_ROCKET_AP_PASSWORD must be empty or at least 8 characters");

/**
 * @brief Return the default Manny SoftAP configuration generated by Kconfig.
 */
static MannyWifiApConfig getDefaultApConfig()
{
    return {
        CONFIG_ROCKET_AP_SSID,
        CONFIG_ROCKET_AP_PASSWORD,
        CONFIG_ROCKET_AP_IP_ADDR,
        CONFIG_ROCKET_AP_NETMASK,
        static_cast<uint8_t>(CONFIG_ROCKET_AP_CHANNEL),
        static_cast<uint8_t>(CONFIG_ROCKET_AP_MAX_CONNECTIONS),
    };
}

MannyBoard::MannyBoard()
    : is_initialized(false),
      nvs_initialized(false),
      networking_initialized(false),
      wifi_started(false),
      sta_netif(nullptr),
      ap_netif(nullptr),
      wifi_ip_address{},
      wifi_mac_address{},
      spi_handler(nullptr) {}

MannyBoard::~MannyBoard() = default;

void MannyBoard::init() {
    const gpio_config_t led_gpio_config = {
        .pin_bit_mask = (1ULL << MANNY_LED_RED_PIN) | (1ULL << MANNY_LED_GREEN_PIN) | (1ULL << MANNY_LED_BUILTIN_PIN),
        .mode         = GPIO_MODE_OUTPUT,
        .pull_up_en   = GPIO_PULLUP_DISABLE,
        .pull_down_en = GPIO_PULLDOWN_DISABLE,
        .intr_type    = GPIO_INTR_DISABLE
    };

    const gpio_config_t actuators_gpio_config = {
        .pin_bit_mask = (1ULL << MANNY_DROGUE_ACTUATOR_PIN) | (1ULL << MANNY_MAIN_ACTUATOR_PIN) | (1ULL << MANNY_BUZZER_PIN),
        .mode         = GPIO_MODE_OUTPUT,
        .pull_up_en   = GPIO_PULLUP_DISABLE,
        .pull_down_en = GPIO_PULLDOWN_DISABLE,
        .intr_type    = GPIO_INTR_DISABLE
    };

    gpio_config(&actuators_gpio_config);
    gpio_config(&led_gpio_config);
    
    gpio_set_level(this->get_main_actuator_pin(), 0);
    gpio_set_level(this->get_drogue_actuator_pin(), 0);


    ESP_ERROR_CHECK(_i2c_bus.init(MANNY_I2C_PORT, MANNY_I2C_SDA_PIN, MANNY_I2C_SCL_PIN));
    ESP_ERROR_CHECK(_spi_bus.init(SPI2_HOST, MANNY_SPI_MOSI_PIN, MANNY_SPI_MISO_PIN, MANNY_SPI_CLK_PIN));

    is_initialized = true;
}

I2CBus* MannyBoard::get_i2c_bus(Sensor sensor) {
    return &_i2c_bus;
}

SPIBus* MannyBoard::get_spi_bus() {
    return &_spi_bus;
}

const char* MannyBoard::get_board_name() const {
    return BOARD_NAME;
}

gpio_num_t MannyBoard::get_i2c_sda_pin() const {
    return MANNY_I2C_SDA_PIN;
}

gpio_num_t MannyBoard::get_i2c_scl_pin() const {
    return MANNY_I2C_SCL_PIN;
}

gpio_num_t MannyBoard::get_barometer2_cs_pin() const {
    return MANNY_BAROMETER2_CS_PIN;
}

gpio_num_t MannyBoard::get_sd_cs_pin() const {
    return MANNY_SD_CS_PIN;
}

gpio_num_t MannyBoard::get_gps_tx_pin() const {
    return MANNY_GPS_TX_PIN;
}

gpio_num_t MannyBoard::get_gps_rx_pin() const {
    return MANNY_GPS_RX_PIN;
}

gpio_num_t MannyBoard::get_arming_pin() const {
    return MANNY_ARMING_PIN;
}

gpio_num_t MannyBoard::get_flash_cs_pin() const {
    return MANNY_FLASH_CS_PIN;
}

gpio_num_t MannyBoard::get_flash_hold_pin() const {
    return MANNY_FLASH_HOLD_PIN;
}

gpio_num_t MannyBoard::get_flash_wp_pin() const {
    return MANNY_FLASH_WP_PIN;
}

gpio_num_t MannyBoard::get_spi_miso_pin() const {
    return MANNY_SPI_MISO_PIN;
}

gpio_num_t MannyBoard::get_spi_mosi_pin() const {
    return MANNY_SPI_MOSI_PIN;
}

gpio_num_t MannyBoard::get_spi_clk_pin() const {
    return MANNY_SPI_CLK_PIN;
}

gpio_num_t MannyBoard::get_barometer_cs_pin() const {
    return MANNY_BAROMETER_CS_PIN;
}

gpio_num_t MannyBoard::get_buzzer_pin() const {
    return MANNY_BUZZER_PIN;
}

gpio_num_t MannyBoard::get_rgb_red_pin() const {
    return MANNY_LED_RED_PIN;
}

gpio_num_t MannyBoard::get_rgb_green_pin() const {
    return MANNY_LED_GREEN_PIN;
}

gpio_num_t MannyBoard::get_rgb_blue_pin() const {
    return MANNY_LED_BLUE_PIN;
}

gpio_num_t MannyBoard::get_main_actuator_pin() const {
    return MANNY_MAIN_ACTUATOR_PIN;
}

gpio_num_t MannyBoard::get_drogue_actuator_pin() const {
    return MANNY_DROGUE_ACTUATOR_PIN;
}

gpio_num_t MannyBoard::get_battery_divider_adc_pin() const {
    return MANNY_BATTERY_DIVIDER_ADC_PIN;
}

int MannyBoard::get_bno055_i2c_address() const {
    return MANNY_BNO055_I2C_ADDRESS;
}

ISPIHandler* MannyBoard::get_spi_handler() const {
    return spi_handler;
}

void MannyBoard::set_spi_handler(ISPIHandler* handler) {
    spi_handler = handler;
}

gpio_num_t MannyBoard::get_lora_cs_pin() const {
    return GPIO_NUM_NC;
}

gpio_num_t MannyBoard::get_lora_aux_pin() const {
    return MANNY_LORA_AUX_PIN;
}

gpio_num_t MannyBoard::get_lora_m0_pin() const {
    return MANNY_LORA_M0_PIN;
}

gpio_num_t MannyBoard::get_lora_m1_pin() const {
    return MANNY_LORA_M1_PIN;
}

gpio_num_t MannyBoard::get_lora_tx_pin() const {
    return MANNY_LORA_TX_PIN;
}

gpio_num_t MannyBoard::get_lora_rx_pin() const {
    return MANNY_LORA_RX_PIN;
}

bool MannyBoard::is_armed() const {
    return true;
}

bool MannyBoard::initNvs() {
    if (nvs_initialized) {
        LOG_INFO(TAG, "NVS already initialized");
        return true;
    }

    // Treat the configured NVS partition as a board dependency and fail early
    // when the partition table does not provide it.
    const esp_partition_t *nvs_partition = esp_partition_find_first(
        ESP_PARTITION_TYPE_DATA,
        ESP_PARTITION_SUBTYPE_DATA_NVS,
        "nvs");
    if (nvs_partition == nullptr) {
        LOG_ERROR(TAG, "Required NVS partition 'nvs' was not found");
        return false;
    }

    esp_err_t ret = nvs_flash_init();
    if (ret == ESP_ERR_NVS_NO_FREE_PAGES || ret == ESP_ERR_NVS_NEW_VERSION_FOUND) {
        LOG_WARNING(TAG, "NVS needs erase before initialization: %s", esp_err_to_name(ret));
        ret = nvs_flash_erase();
        if (ret != ESP_OK) {
            LOG_ERROR(TAG, "nvs_flash_erase failed: %s", esp_err_to_name(ret));
            return false;
        }
        ret = nvs_flash_init();
    }
    if (ret != ESP_OK) {
        LOG_ERROR(TAG, "nvs_flash_init failed: %s", esp_err_to_name(ret));
        return false;
    }

    nvs_initialized = true;
    LOG_INFO(TAG, "NVS initialized from partition '%s'", nvs_partition->label);
    return true;
}

bool MannyBoard::isNvsReady() const {
    return nvs_initialized;
}

bool MannyBoard::initNetworking() {
    if (networking_initialized) {
        LOG_INFO(TAG, "Networking already initialized");
        return true;
    }

    // WiFi depends on NVS, esp-netif, and the default event loop. Keeping this
    // sequence here prevents callers from duplicating low-level ESP-IDF setup.
    if (!initNvs()) {
        return false;
    }

    esp_err_t ret = esp_netif_init();
    if (ret != ESP_OK && ret != ESP_ERR_INVALID_STATE) {
        LOG_ERROR(TAG, "esp_netif_init failed: %s", esp_err_to_name(ret));
        return false;
    }
    if (ret == ESP_ERR_INVALID_STATE) {
        LOG_INFO(TAG, "esp_netif already initialized");
    }

    ret = esp_event_loop_create_default();
    if (ret != ESP_OK && ret != ESP_ERR_INVALID_STATE) {
        LOG_ERROR(TAG, "esp_event_loop_create_default failed: %s", esp_err_to_name(ret));
        return false;
    }
    if (ret == ESP_ERR_INVALID_STATE) {
        LOG_INFO(TAG, "default event loop already exists");
    }

    wifi_init_config_t wifi_init_config = WIFI_INIT_CONFIG_DEFAULT();
    ret = esp_wifi_init(&wifi_init_config);
    if (ret != ESP_OK && ret != ESP_ERR_WIFI_INIT_STATE) {
        LOG_ERROR(TAG, "esp_wifi_init failed: %s", esp_err_to_name(ret));
        return false;
    }
    if (ret == ESP_ERR_WIFI_INIT_STATE) {
        LOG_INFO(TAG, "WiFi already initialized");
    }

    networking_initialized = true;
    return true;
}

bool MannyBoard::startWifiSta() {
    if (!initNetworking()) {
        return false;
    }

    if (sta_netif == nullptr) {
        sta_netif = esp_netif_create_default_wifi_sta();
    }

    esp_err_t ret = esp_wifi_set_mode(WIFI_MODE_STA);
    if (ret != ESP_OK) {
        LOG_ERROR(TAG, "esp_wifi_set_mode STA failed: %s", esp_err_to_name(ret));
        return false;
    }

    ret = esp_wifi_start();
    if (ret != ESP_OK && ret != ESP_ERR_WIFI_NOT_STOPPED) {
        LOG_ERROR(TAG, "esp_wifi_start failed: %s", esp_err_to_name(ret));
        return false;
    }
    if (ret == ESP_ERR_WIFI_NOT_STOPPED) {
        LOG_INFO(TAG, "WiFi STA already started");
    }

    wifi_started = true;
    wifi_ip_address[0] = '\0';
    uint8_t mac[6] = {};
    if (esp_wifi_get_mac(WIFI_IF_STA, mac) == ESP_OK) {
        snprintf(wifi_mac_address, sizeof(wifi_mac_address), "%02x:%02x:%02x:%02x:%02x:%02x",
                 mac[0], mac[1], mac[2], mac[3], mac[4], mac[5]);
    }
    ret = esp_wifi_disconnect();
    if (ret != ESP_OK && ret != ESP_ERR_WIFI_NOT_INIT && ret != ESP_ERR_WIFI_CONN) {
        LOG_WARNING(TAG, "esp_wifi_disconnect returned: %s", esp_err_to_name(ret));
    }
    return true;
}

bool MannyBoard::startWifiSoftAp() {
    if (!initNetworking()) {
        return false;
    }

    // AP credentials and network parameters come from Kconfig-generated
    // sdkconfig values. Private overrides belong in the ignored sdkconfig file.
    const MannyWifiApConfig cfg = getDefaultApConfig();

    if (ap_netif == nullptr) {
        ap_netif = esp_netif_create_default_wifi_ap();
        if (ap_netif == nullptr) {
            LOG_ERROR(TAG, "Failed to create default WiFi AP netif");
            return false;
        }
    }

    wifi_config_t wifi_config = {};
    snprintf(reinterpret_cast<char *>(wifi_config.ap.ssid), sizeof(wifi_config.ap.ssid), "%s", cfg.ssid);
    snprintf(reinterpret_cast<char *>(wifi_config.ap.password), sizeof(wifi_config.ap.password), "%s", cfg.password);
    wifi_config.ap.ssid_len = strlen(cfg.ssid);
    wifi_config.ap.channel = cfg.channel;
    wifi_config.ap.max_connection = cfg.max_connections;
    wifi_config.ap.authmode = strlen(cfg.password) == 0 ? WIFI_AUTH_OPEN : WIFI_AUTH_WPA2_WPA3_PSK;

    esp_err_t ret = esp_wifi_set_mode(WIFI_MODE_AP);
    if (ret != ESP_OK) {
        LOG_ERROR(TAG, "esp_wifi_set_mode AP failed: %s", esp_err_to_name(ret));
        return false;
    }

    ret = esp_netif_dhcps_stop(ap_netif);
    if (ret != ESP_OK && ret != ESP_ERR_ESP_NETIF_DHCP_ALREADY_STOPPED) {
        LOG_ERROR(TAG, "esp_netif_dhcps_stop failed: %s", esp_err_to_name(ret));
        return false;
    }

    esp_netif_ip_info_t ip_info = {};
    if (esp_netif_str_to_ip4(cfg.ip, &ip_info.ip) != ESP_OK ||
        esp_netif_str_to_ip4(cfg.ip, &ip_info.gw) != ESP_OK ||
        esp_netif_str_to_ip4(cfg.netmask, &ip_info.netmask) != ESP_OK) {
        LOG_ERROR(TAG, "Invalid SoftAP IP configuration: ip=%s netmask=%s", cfg.ip, cfg.netmask);
        return false;
    }

    ret = esp_netif_set_ip_info(ap_netif, &ip_info);
    if (ret != ESP_OK) {
        LOG_ERROR(TAG, "esp_netif_set_ip_info AP failed: %s", esp_err_to_name(ret));
        return false;
    }

    ret = esp_netif_dhcps_start(ap_netif);
    if (ret != ESP_OK && ret != ESP_ERR_ESP_NETIF_DHCP_ALREADY_STARTED) {
        LOG_ERROR(TAG, "esp_netif_dhcps_start failed: %s", esp_err_to_name(ret));
        return false;
    }

    ret = esp_wifi_set_config(WIFI_IF_AP, &wifi_config);
    if (ret != ESP_OK) {
        LOG_ERROR(TAG, "esp_wifi_set_config AP failed: %s", esp_err_to_name(ret));
        return false;
    }

    ret = esp_wifi_start();
    if (ret != ESP_OK && ret != ESP_ERR_WIFI_NOT_STOPPED) {
        LOG_ERROR(TAG, "esp_wifi_start AP failed: %s", esp_err_to_name(ret));
        return false;
    }
    if (ret == ESP_ERR_WIFI_NOT_STOPPED) {
        LOG_INFO(TAG, "WiFi SoftAP already started");
    }

    wifi_started = true;
    snprintf(wifi_ip_address, sizeof(wifi_ip_address), "%s", cfg.ip);
    uint8_t mac[6] = {};
    if (esp_wifi_get_mac(WIFI_IF_AP, mac) == ESP_OK) {
        snprintf(wifi_mac_address, sizeof(wifi_mac_address), "%02x:%02x:%02x:%02x:%02x:%02x",
                 mac[0], mac[1], mac[2], mac[3], mac[4], mac[5]);
    }
    LOG_INFO(TAG, "SoftAP started: ssid=%s ip=%s channel=%u max_sta=%u",
             cfg.ssid, cfg.ip, cfg.channel, cfg.max_connections);
    return true;
}

bool MannyBoard::stopWifi() {
    if (!networking_initialized || !wifi_started) {
        return true;
    }
    esp_err_t ret = esp_wifi_stop();
    if (ret != ESP_OK && ret != ESP_ERR_WIFI_NOT_INIT) {
        LOG_ERROR(TAG, "esp_wifi_stop failed: %s", esp_err_to_name(ret));
        return false;
    }
    wifi_started = false;
    wifi_ip_address[0] = '\0';
    return true;
}

bool MannyBoard::isWifiConnected() const {
    return wifi_started;
}

const char* MannyBoard::getWifiIpAddress() const {
    return wifi_ip_address;
}

const char* MannyBoard::getWifiMacAddress() const {
    return wifi_mac_address;
}

bool MannyBoard::initBluetooth() {
    LOG_INFO(TAG, "Bluetooth is not used by Manny ground services yet");
    return true;
}

bool MannyBoard::stopBluetooth() {
    return true;
}

void MannyBoard::init_sensor_test_pins() {}

void MannyBoard::signal_sensor_ok(IBoardHardware::Sensor sensor) {}
