#pragma once
#include <IMUData.hpp>
#include <BNO055SensorInterface.hpp>
#include <ISensor.hpp>

/**
 * @brief BNO055 sensor class
 * 
 */
class BNO055Sensor : public ISensor
{
public:
    /** @brief Construct a new BNO055 sensor wrapper. */
    BNO055Sensor();

    /**
     * @brief Initialize the BNO055 device and prepare it for measurements.
     * @return true on success, false otherwise.
     */
    bool init() override;
    bool updateData() override;
    bool hardwareTest();

    /**
     * @brief Getter for the sensor data
     * 
     * @return a shared pointer to the IMUData structure containing the latest readings 
     */
    std::shared_ptr<IMUData> getData();

private:
    // Interface to the BNO055 sensor using low-level APIs
    BNO055SensorInterface _bno_interface;

    // Data generated by the sensor
    std::shared_ptr<IMUData> _data;
};